#%RAML 1.0
---
title: FirstTap
baseUri: http://firsttap.appspot.com/v1
version: 1
/health:
  description: Check system liveness
  get:
    description: |
      **Return 200 to confirm system is live**
    responses:
      200:
        body:
          application/json:
            example: !include ./includes/responses/health-response.json

/signup:
    description: Sign up new users using existing employee id
    post:
      description: |
        **Store a new employee in the FirstTap system**

        This assumes a unique id for each user and stores them in the system DB.
        Core employee data is required and the route will fail if values are missing from the body.

        The employee name and a usage token valid for 5 minutes will be returned. This must be included in the headers of all further API calls.
      body:
        application/json:
          type: !include ./includes/schemas/signup-query.json
          examples:
            basic:
              displayName: Basic user info
              value: !include ./includes/requests/signup-query.json
      responses:
        200:
          body:
            application/json:
              example: !include ./includes/responses/login-success.json
        400:
          body:
            application/json:
              example: !include ./includes/responses/bad-req.json
        401:
          body:
            application/json:
              example: !include ./includes/responses/auth-fail.json
        500:
          body:
            application/json:
              example: !include ./includes/responses/datastore-err.json

/login:
    description: Log in existing users using existing employeeId and pin code
    post:
      description: |
        **Log in an existing user**

        Retrieve a valid user token by logging in with a  valid employeeId and pincode.
      body:
        application/json:
          type: !include ./includes/schemas/login-query.json
          examples:
            basic:
              displayName: Basic user info
              value: !include ./includes/requests/login-query.json
      responses:
        200:
          body:
            application/json:
              example: !include ./includes/responses/login-success.json
        400:
          body:
            application/json:
              example: !include ./includes/responses/bad-req.json
        401:
          body:
            application/json:
              example: !include ./includes/responses/auth-fail.json
        500:
          body:
            application/json:
              example: !include ./includes/responses/datastore-err.json
